---


- name: Copy template for kubelet service 
  template: >
      src=kube-proxy.service.j2
      dest=/etc/systemd/system/kube-proxy.service
  notify:
    - reload systemd daemon
    - enable kube-proxy
    - start kube-proxy

