- name: reload systemd daemon
  command: systemctl daemon-reload

- name: enable docker service
  command: systemctl enable docker

- name: restart docker
  service: >
    name=docker
    state=restarted
    enabled=yes

- name: enable kubelet
  command: systemctl enable kubelet

- name: start kubelet
  service: >
    name=kubelet
    state=restarted
    enabled=yes

- name: enable kube-proxy
  command:  systemctl enable kube-proxy

- name: start kube-proxy
  service: >
    name=kube-proxy
    state=restarted
    enabled=yes

  
