---

# Install cfssl and cfssljson
#

- name: Install cfssl
  get_url:
          url: https://pkg.cfssl.org/R1.2/cfssl_linux-amd64
          dest: /usr/local/bin/cfssl

- name: change permission
  file: 
      path: /usr/local/bin/cfssl
      owner: root
      group: root
      mode: 0755

- name: Install cfssljson
  get_url: 
         url: https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64
         dest: /usr/local/bin/cfssljson

- name: change permissions cfssljson
  file: 
      path: /usr/local/bin/cfssljson
      owner: root
      group: root
      mode: 0755   

- include: ca-setup.yml
