--- 

# Main file for deploying the complete stack
#
#- name: Generate certs on Jump host #Has to change
#  hosts: tag_Name_Jump_node
#  remote_user: ubuntu
#  become: True

#  roles:
#     - localhost


- name: Initial configuration on all hosts
  hosts: ec2
  remote_user: ubuntu 
  become: True
  
  roles:
    - common

- name: Setup etcd 
  hosts: tag_Node_etcd
  remote_user: ubuntu
  become: True

  roles:
   - etcd

- name: Setup kube servers
  hosts: tag_Node_kubeM
  remote_user: ubuntu
  become: True

  roles:
    - kube-master


- name: Setup worker nodes
  hosts: tag_Node_worker
  remote_user: ubuntu
  become: True

  roles:
    - workers
