---

- name: Create etcd directory
  file:
     path: /etc/etcd/
     state: directory
     mode: 0755 

- name: Copy cert files from home dir
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
     - { src: '/home/ubuntu/ca.pem', dest: '/etc/etcd/' }
     - { src: '/home/ubuntu/kubernetes-key.pem', dest: '/etc/etcd/' }
     - { src: '/home/ubuntu/kubernetes.pem', dest: '/etc/etcd/' }

- name: Download etcd binaries 
  get_url: 
     url: https://github.com/coreos/etcd/releases/download/v3.1.0/etcd-v3.1.0-linux-amd64.tar.gz
     dest: /tmp/etcd-v3.1.0-linux-amd64.tar.gz
     owner: ubuntu
     group: ubuntu

#- name: Untar 
  #unarchive:
     #src: /tmp/etcd-v3.1.0-linux-amd64.tar.gz
     #dest: /tmp 
     #remote_src: True

- name: Untar 
  shell: "cd /tmp; tar -xvf /tmp/etcd-v3.1.0-linux-amd64.tar.gz"


- name: Copy etcd to bin directory
  copy: >
     src=/tmp/etcd-v3.1.0-linux-amd64/{{item}} 
     dest=/usr/bin/{{item}}
     remote_src=true
  with_items:
     - etcd
     - etcdctl

- name: Create directory for etcd persistent storage
  file: 
     path: /var/lib/etcd
     state: directory 
     mode: 0755 

- name: Create directory for systemd files
  file:
     path:  /etc/systemd/system
     state: directory 
     mode: 0755

- name: Copy systemd template to systemd dir
  template: 
      src: etcd.service.j2
      dest: /etc/systemd/system/etcd.service
      mode: 0644
  notify: restart etcd

- name: Start etcd services1
  command: systemctl daemon-reload

- name: Start etcd services2
  command: systemctl enable etcd

- name: Start etcd services3
  command: systemctl start etcd


